.TH TORK\-REMOTE 1 2012\-09\-26 18.2.3
.SH NAME
.PP
tork\-remote \- controls 
.BR tork (1) 
programs
.SH SYNOPSIS
.PP
\fB\fCtork\-remote\fR [\fIOPTION\fP]... \fIPROGRAM\fP
.SH DESCRIPTION
.PP
This program reads lines from its stdin and sends them to the given \fIPROGRAM\fP,
which must already be running in the same working directory as this program.
It also prints lines, received in response, from the given \fIPROGRAM\fP either
to stdout if they are valid single\-line JSON arrays or to stderr otherwise.
.SH OPTIONS
.TP
\fB\fC\-h\fR, \fB\fC\-\-help\fR
Show this help manual.
.SH EXIT STATUS
.TP
1
Could not connect to the \fIPROGRAM\fP\&.
.TP
2
Lost connection to the \fIPROGRAM\fP\&.
.SH SEE ALSO
.PP
.BR tork (1), 
.BR tork-driver (1), 
.BR tork-engine (1), 
.BR tork-master (1)